token = "" # Токен сообщества ВКонтакте

buttons_text = "Nigga" # Текст кнопки
message_text = "🤘🏻" # Текст сообщения. Можно вписать любой, он не будет повторяться максимальное количество раз
picture = "" # Отправляет картинку

logging_level = "DEBUG"
delay = 1.0 # Интервал перед следующей отправкой
