token = "" # Токен сообщества ВКонтакте

buttons_text = "Nigga" # Текст кнопки
message_text = "🤘🏻" # Текст сообщения. Можно вписать любой, он не будет повторяться максимальное количество раз
attachment = "" # Отправляет любое из перечисленных вложений: 'photo' — фото, 'video' — видео, 'audio' — аудио, 'doc' — докумен, 'wall' — пост на стене. Формат подписи такой: <Вложение><Владелец этого вложения>_<id вложения>, пример: photo514714577_457311228

logging_level = "DEBUG"
delay = 1.0 # Интервал перед следующей отправкой
