token = "" # Токен сообщества ВКонтакте

buttons_text = "Nigga"
message_text = "@all 🤘🏻" # Текст сообщения. Можно вписать любой, он не будет повторяться максимальное количество раз
picture = "" # Отправляет картинку

logging_level = "DEBUG"
delay = 1.0
