token = "" # Токен сообщества ВКонтакте

buttons_text = "Nigga"
message_text = "@all 🤘🏻" # Текст сообщения. Можно вписать любой, он не будет повторяться максимальное количество раз
picture = "https://m.myporno-tv.com/contents/videos_screenshots/36000/36638/426x240/5.jpg" # Отправляет картинку

logging_level = "DEBUG"
delay = 1.0
