token = "" # Токен сообщества ВКонтакте

replay_message = "0" # Повторяет текст сообщения максимальное количество раз. 0 - не будет работать, 1 - будет работать
replay_b = "4096" # Количество повторений в bytes. Рекомендуемое значение - 4096

call_by_id = "0" # Можно будет вызывать бота через @. 0 - будет спамить только при добавление в беседу, чтобы перезапустить, нужно кикнуть и добавить в беседу(если авто рестарт выключен). 1 - будет спамить, если вызвать через @ или кнопку
stop_sending_messages_by_counter = "-1" # Отправляет n-ое количество сообщений, а после перестаёт работать. Чтобы спамило бесконечно, нужно ставить отрицательные числа (-1 к примеру)

buttons_enable = "1" # Возможность включать и выключать кнопки
buttons_text = "Button" # Текст кнопки
button_color1 = "0" # Цвет кнопки 1. 0 - зелёная, 1 - красная, 2 - серая, 3 - синяя.
button_color2 = "1" # Цвет кнопки 2. 0 - зелёная, 1 - красная, 2 - серая, 3 - синяя.
button_color3 = "2" # Цвет кнопки 3. 0 - зелёная, 1 - красная, 2 - серая, 3 - синяя.
button_color4 = "3" # Цвет кнопки 4. 0 - зелёная, 1 - красная, 2 - серая, 3 - синяя.

message_text = "🤘🏻" # Текст сообщения
attachment = "" # Отправляет любое из перечисленных вложений: 'photo' — фото, 'video' — видео, 'audio' — аудио, 'doc' — докумен, 'wall' — пост на стене. Формат подписи такой: <Вложение><Владелец этого вложения>_<id вложения>, пример: photo514714577_457311228

delay = "1.0" # Интервал перед отправкой сообщения
delay_kill = "10.0" # Интервал следующего спама после того, как выдало ошибку о спаме, или чего-то другого
kill_bot = "0" # Убивает бота при ошибке спама. Чтобы повторно запустить, нужно, или его вызвать(если конечно эта функция включена), или добавить его повторно. 0 - будет его перезапускать автоматически с задержкой (delay_kill), 1 - будет вырубать его

logging_level = "DEBUG"
