token = "" # Токен сообщества ВКонтакте

replay_message = "0" # Повторяет текст сообщения максимальное количество раз. 0 - не будет работать, 1 - будет работать
replay_b = "4096" # Количество повторений в bytes. Рекомендуемое значение - 4096

call_by@ = "0" # Можно будет вызывать бота через @. 0 - будет спамить только при добавление в беседу, чтобы перезапустить, нужно кикнуть и добавить в беседу. 1 - будет спамить, если вызвать через @ или кнопку

buttons_text = "Button" # Текст кнопки
message_text = "🤘🏻" # Текст сообщения
attachment = "" # Отправляет любое из перечисленных вложений: 'photo' — фото, 'video' — видео, 'audio' — аудио, 'doc' — докумен, 'wall' — пост на стене. Формат подписи такой: <Вложение><Владелец этого вложения>_<id вложения>, пример: photo514714577_457311228

logging_level = "DEBUG"
delay = "" # Интервал перед отправкой сообщения
delay_kill = "" # Интервал следующего спама после того, как выдало ошибку о спаме, или чего-то другого
