token = "" # Токен сообщества ВКонтакте

buttons_text = "vto.pe"
message_text = "@all 🤘🏻" # Текст сообщения. Если короче 1024 байтов - будет повторён максимальное количество раз

logging_level = "DEBUG"
delay = 1.0
